---
title: "Make Your Computational Analysis Citable 2"
description: |
  This post introduces the steps needed by academic and non-acadmics to make their computational analysis citable regardless of being published in journals.
author:
  - name: Batool Almarzouq 
    url:  https://batoolmm.netlify.app/
    affiliation: The University of Liverpool
    affiliation_url: https://www.liverpool.ac.uk/
date: 06-23-2021
output:
  distill::distill_article:
    self_contained: false
---

Although there are overwhelming resources about licencing and citation for R software packages, there's less attention paid to making non-package (data science) code in R citable. Academics and researchers who want to embrace Open Science practices are mostly unaware of how to make their R code citable before publishing in academic journals and what kind of licence they may use to protect the intellectual property of their work. 

Books and published journal articles have always been supplemented with DOIs (digital object identifiers), a key element in the process of research and academic discourse but there's less attention paid to unpublished computational analysis, which is usually abandoned in GitHub (or in someone's drive).

As a researcher, we often spend long time collecting data  

- Reproducibility 
- License 
- Zenodo
- Publishing throughout the research cycle - Open Science


```{r}
plot(1:10)
```
This is noted [^key]

<aside>
This will not just improve reproducibility but also collaboration and transparancy. 
</aside>



[^key]: it was meant to builds on other websites 



